---
# Main tasks file
- name: "Fail if preferred_syslog_daemon is not rsyslog or syslog-ng"
  ansible.builtin.fail:
    msg: "Only rsyslog or syslog-ng is supported as a syslog daemon"
  when: "preferred_syslog_daemon not in ['rsyslog', 'syslog-ng']"

- name: "Fail if graylog_protocol is not tcp or udp"
  ansible.builtin.fail:
    msg: "Only TCP or UDP protocol is supported to forward logs to Graylog"
  when: "graylog_protocol not in ['tcp', 'udp']"

- name: "Print the rsyslog package facts"
  ansible.builtin.debug:
    var: "ansible_facts.packages['rsyslog']"

- name: "Print the syslog-ng package facts"
  ansible.builtin.debug:
    var: "ansible_facts.packages['syslog-ng']"

- name: "Set missing_rsyslog and missing_syslog_ng variable"
  set_fact:
    missing_rsyslog: "{{ ansible_facts.packages[ 'rsyslog' ] is not defined }}"
    missing_syslog_ng: "{{ ansible_facts.packages[ 'syslog-ng' ] is not defined }}"

- name: "Fail if both syslog daemons are installed"
  ansible.builtin.fail:
    msg: "Both rsyslog and syslog-ng are installed. Please choose only one syslog daemon"
  when: "not missing_rsyslog and not missing_syslog_ng"

- name: "If none of the syslog daemons are installed, install the preferred one"
  include_tasks: "set-up-{{ preferred_syslog_daemon }}.yml"
  when: "missing_rsyslog and missing_syslog_ng"

- name: "If rsyslog is installed, configure it"
  include_tasks: "set-up-rsyslog.yml"
  when: "not missing_rsyslog and missing_syslog_ng"

- name: "If syslog-ng is installed, configure it"
  include_tasks: "set-up-syslog-ng.yml"
  when: "missing_rsystlog and not missing_syslog_ng"
